services:

  postgres-db:
    image: postgres:15-alpine
    container_name: financial-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "127.0.0.1:5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres-db
    restart: unless-stopped


  simulations-seeder:
    build:
      context: .
      dockerfile: src/simulations/Dockerfile.seeder
    container_name: simulations-seeder
    depends_on:
      - postgres-db
    environment:
      - BANK_DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/bank_db
      - INVEST_DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/invest_db
      - RUBLE_DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/ruble_db
    env_file:
      - .env

  bank-worker:
    build:
      context: .
      dockerfile: src/simulations/workers/bank_eod/Dockerfile
    container_name: bank-worker
    depends_on:
      - postgres-db
    environment:
      - BANK_DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/bank_db
    env_file:
      - .env
    restart: unless-stopped

  invest-worker:
    build:
      context: .
      dockerfile: src/simulations/workers/invest_eod/Dockerfile
    container_name: invest-worker
    depends_on:
      - postgres-db
    environment:
      - INVEST_DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/invest_db
    env_file:
      - .env
    restart: unless-stopped

  ruble-worker:
    build:
      context: .
      dockerfile: src/simulations/workers/ruble_eod/Dockerfile
    container_name: ruble-worker
    depends_on:
      postgres-db:
        condition: service_started
    environment:
      - RUBLE_DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/ruble_db
    env_file:
      - .env
    restart: unless-stopped

  simulation-api:
    build:
      context: .
      dockerfile: src/simulations/api/Dockerfile
    container_name: simulation-api
    depends_on:
      - postgres-db
    ports:
      - "127.0.0.1:8002:8002"
    environment:
      - BANK_DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/bank_db
      - INVEST_DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/invest_db
      - RUBLE_DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/ruble_db
    env_file:
      - .env
    restart: unless-stopped

  admin-server:
    build:
      context: ./src/admin_server/fastapi
      dockerfile: Dockerfile
    container_name: admin-server
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH}
    env_file:
      - .env
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: caddy-server
    restart: unless-stopped
    depends_on:
      - admin-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  postgres_data:
  pgadmin_data:
  caddy_data:
  caddy_config:
